import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Main page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='main'>
          <div className='announcement_button'>
            <h3>
              <span id='bolder'>Introducing the Helium Foundation</span> Head the Announcement <span className="material-symbols-sharp pointer">
  north_east
</span>
            </h3>
          </div>
          <div id='Headline'>
            <h1>
              People- Powered Networks.
            </h1>
          </div>
          <div className='text'>
            <h2 >Start a wireless Revolution</h2>
          </div>
          <div className='p_tag'>
            <h2>Powered by the Helium Blockchain, The People's Network represents a paradigm shift for decentralized wireless infrastructure.</h2>
          </div>
        </div>
      </main>
    </>
  )
}
